### ISSUE TITLE
Upload the latest code

### ISSUE THREAD

**Issue by sburdka** [Chetan3321/IOT-Based-Health-Monitoring-System#1]
Hi @Chetan3321 
Upload the files, so that we could workout the project version.

## Timeline

| Sr No | Resolve Date | Close Date |
|-------|----------------|-------------|
|20YY/MM/DD | 20YY/MM/DD | 20YY/MM/DD|

## Purpose / Goal
* Release of Stable Code for Health Monitoring System

## Details / Background
*  Remote Dashboard for Heart Beats And Temperature Monitoring System

## Deliverables
* Stable Code

**Comment by Chetan3321** [comment]
Hi@suyog44
File are uploaded, if there is any issues please let me know.

**Comment by sburdka** [comment]
> Hi@suyog44 File are uploaded, if there is any issues.

Hi @Chetan3321 ,

Thanks for completing the job within timeline.,

Regards,             
Suyog
